In [217]:
import numpy as np
import pandas as pd
import os

os.chdir('C:\\Users\\82105\\Desktop\\Data Science Lab\\Final Project')

### Concat

In [218]:
dup = pd.read_excel('김보아_duplicated_최종.xlsx')
nodup = pd.read_excel('박민지_unique_합치기전.xlsx')

In [219]:
dup.head()

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,74913,460000000354,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
1,73874,462000000232,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
2,72963,453000000184,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
3,72798,568000000387,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
4,66578,479000000303,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0

In [220]:
dup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8422 entries, 0 to 8421
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   정책ID       8422 non-null   int64
 1   정책서비스ID    8422 non-null   object
 2   서비스명       8422 non-null   object
 3   신청절차       4144 non-null   object
 4   자녀         1982 non-null   object
 5   수집유형       0 non-null      float64
 6   가구원        214 non-null    object
 7   성별         386 non-null    object
 8   학력         0 non-null      float64
 9   직장         1992 non-null   object
 10  결혼         152 non-null    object
 11  지원유형       8282 non-null   object
 12  지역(시도)     8422 non-null   object
 13  관심상황특성     2087 non-null   object
 14  자녀상세       1436 non-null   object
 15  직장상세       1324 non-null   object
 16  지원유형상세     7979 non-null   object
 17  지역(시군구)    8398 non-null   object
 18  대상특성상세     793 non-null    object
 19  대상특성       6252 non-null   object
 20  대상연령시작     8422 non-null   int64
 21  대상연령끝      8422 non-null   int64
 22  중위소득기준-시작  8422 non-null   int64
 23  중위소득기준-종료  8422 non-null   int64
dtypes: float64(2), int64(5), object(17)
memory usage: 1.5+ MB

In [221]:
dup = dup.astype({'정책ID': int, '대상연령시작': int, '대상연령끝': int, '중위소득기준-시작': int, '중위소득기준-종료': int})
dup.head()

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,74913,460000000354,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
1,73874,462000000232,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
2,72963,453000000184,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
3,72798,568000000387,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0
4,66578,479000000303,고효율 어선 유류절감 장비 지원,오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,"A04-05-00, A04-06-00",A09-01-00,전체,연근해-구획어업인,농축수산인,0,99,0,0

In [222]:
nodup.head()

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,60016,480000000383,건강가정 복지증진 및 지원,온라인,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-03-04,A09-09-01",NaN,NaN,NaN,0,99,0,0
1,60022,480000000433,다문화가정 인터넷 사용요금 지원,오프라인,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-00,NaN,NaN,다문화가족,0,99,0,0
2,60042,480000000477,수의사 연수교육 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-09-01, A09-01-00",NaN,NaN,농축수산인,0,99,0,0
3,60058,480000000498,국공립 어린이집 확충 지원,NaN,있음,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-09-01,NaN,NaN,NaN,0,5,0,0
4,60068,495000000215,2018년 농산물마케팅 지원(농산물마케팅 지원사업),온라인,NaN,NaN,NaN,NaN,NaN,"중소기업,소상공인,근로자/직장인,예비창업자",...,NaN,"A04-02-01,A04-02-03,A04-02-03,A04-03-01,A04-03...",NaN,NaN,NaN,기관/시설,0,99,0,0

In [223]:
nodup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6576 entries, 0 to 6575
Data columns (total 24 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   정책ID       6576 non-null   int64
 1   정책서비스ID    6576 non-null   object
 2   서비스명       6576 non-null   object
 3   신청절차       2751 non-null   object
 4   자녀         1989 non-null   object
 5   수집유형       14 non-null     object
 6   가구원        216 non-null    object
 7   성별         221 non-null    object
 8   학력         67 non-null     object
 9   직장         2318 non-null   object
 10  결혼         127 non-null    object
 11  지원유형       6041 non-null   object
 12  지역(시도)     0 non-null      float64
 13  관심상황특성     460 non-null    object
 14  자녀상세       168 non-null    object
 15  직장상세       2245 non-null   object
 16  지원유형상세     5625 non-null   object
 17  지역(시군구)    0 non-null      float64
 18  대상특성상세     358 non-null    object
 19  대상특성       4419 non-null   object
 20  대상연령시작     6576 non-null   int64
 21  대상연령끝      6576 non-null   int64
 22  중위소득기준-시작  6576 non-null   int64
 23  중위소득기준-종료  6576 non-null   int64
dtypes: float64(2), int64(5), object(17)
memory usage: 1.2+ MB

In [224]:
nodup = nodup.astype({'정책ID': int, '대상연령시작': int, '대상연령끝': int, '중위소득기준-시작': int, '중위소득기준-종료': int})
nodup.head()

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,60016,480000000383,건강가정 복지증진 및 지원,온라인,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-03-04,A09-09-01",NaN,NaN,NaN,0,99,0,0
1,60022,480000000433,다문화가정 인터넷 사용요금 지원,오프라인,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-00,NaN,NaN,다문화가족,0,99,0,0
2,60042,480000000477,수의사 연수교육 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-09-01, A09-01-00",NaN,NaN,농축수산인,0,99,0,0
3,60058,480000000498,국공립 어린이집 확충 지원,NaN,있음,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-09-01,NaN,NaN,NaN,0,5,0,0
4,60068,495000000215,2018년 농산물마케팅 지원(농산물마케팅 지원사업),온라인,NaN,NaN,NaN,NaN,NaN,"중소기업,소상공인,근로자/직장인,예비창업자",...,NaN,"A04-02-01,A04-02-03,A04-02-03,A04-03-01,A04-03...",NaN,NaN,NaN,기관/시설,0,99,0,0

In [225]:
policy = pd.concat([dup, nodup]).sort_values(by='정책ID', ascending=False, ignore_index=True)
policy

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,75000,458000000210,6차산업 자금 융자 지원,NaN,NaN,NaN,NaN,NaN,NaN,"중소기업,예비창업자",...,NaN,"A04-02-01,A04-02-01,A04-02-03,A04-02-03,A04-02...",NaN,NaN,축산업인,"농축수산인,기관/시설",0,99,0,0
1,74999,458000000382,장애 입양아동 의료비 지원,오프라인,있음,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-03-03,A09-09-01, A09-01-00",NaN,NaN,"장애인,입양가정",6,12,0,0
2,74998,000000402300,행려자 귀향여비 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-00,NaN,NaN,NaN,0,99,0,0
3,74997,458000000253,농산물 우수관리 시설 보완 지원(GAP),오프라인,NaN,NaN,NaN,NaN,NaN,"중소기업,소상공인,예비창업자",...,NaN,"A04-02-01,A04-02-03,A04-02-04,A04-02-04,A04-02...",A09-01-00,NaN,NaN,"농축수산인,기관/시설",0,99,0,0
4,74996,644000000251,충청남도 공공갈등 예방과 조정 지원,NaN,있음,NaN,NaN,NaN,NaN,중소기업,...,NaN,"A04-02-01,A04-02-02,A04-03-01,A04-03-02,A04-04...",A09-09-01,NaN,NaN,NaN,0,99,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14993,60005,485000000371,의료기관 결핵 환자 접촉자 검진비 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-03-03,전체,NaN,NaN,0,99,0,0
14994,60004,485000000370,의료급여수급자 일반 건강검진 지원,NaN,NaN,NaN,"무주택 세대주, 무주택 세대원, 주택 세대주, 주택 세대원",NaN,NaN,NaN,...,NaN,NaN,"A09-03-03, A09-01-00",전체,NaN,기관/시설,0,99,0,40
14995,60003,485000000363,유망 예비 농업인 및 우수 농업경영인 대상 창업 자금 등 융자 지원(후계농업경영인 육성),NaN,NaN,NaN,NaN,무관,NaN,NaN,...,NaN,NaN,A09-01-02,전체,NaN,농축수산인,18,49,0,0
14996,60002,485000000361,우수 후계농업경영인 추가 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-02,전체,NaN,농축수산인,0,99,0,0
14997,60001,483000000355,농산물 우수관리제도GAP 인증신청 수수료 지원,NaN,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업, 근로자/직장인",...,NaN,"A04-05-00, A04-06-00",A09-01-00,나주시,NaN,농축수산인,0,99,0,0

In [226]:
# 정책ID 누락 확인
for i in range(60001,75001):
    if i not in list(policy['정책ID']):
        print(i)

61363
61689

In [228]:
plus = pd.read_excel('정책정보_2021-10-27.xlsx')
plus.head()

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,75000.0,458000000000.0,6차산업 자금 융자 지원,NaN,NaN,NaN,NaN,무관,무관,중소기업,...,NaN,"농업/축산업/어업, 농업/축산업/어업, 경영/사무/금융/보험직, 농업/축산업/어업,...",NaN,서천군,축산업인,"농축수산인, 기관/시설",0.0,99.0,0.0,0.0
1,74999.0,458000000000.0,장애 입양아동 의료비 지원,오프라인,있음,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,의료,서천군,NaN,"장애인, 입양가정",6.0,12.0,0.0,0.0
2,74998.0,402300.0,행려자 귀향여비 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,서천군,NaN,NaN,0.0,99.0,0.0,0.0
3,74997.0,458000000000.0,농산물 우수관리 시설 보완 지원(GAP),오프라인,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업",...,NaN,NaN,NaN,서천군,NaN,"농축수산인, 기관/시설",0.0,99.0,0.0,0.0
4,74996.0,644000000000.0,충청남도 공공갈등 예방과 조정 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"공공/행정/국방/방위산업, 공공/행정/국방/방위산업, 공공/행정/국방/방위산업",NaN,전체,NaN,NaN,0.0,99.0,0.0,0.0

In [229]:
plus = plus.astype({'정책ID': int})
policy = pd.concat([policy, plus[plus['정책ID']==61363], plus[plus['정책ID']==61689]]).sort_values(by='정책ID', ascending=False, ignore_index=True)
policy

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,75000,458000000210,6차산업 자금 융자 지원,NaN,NaN,NaN,NaN,NaN,NaN,"중소기업,예비창업자",...,NaN,"A04-02-01,A04-02-01,A04-02-03,A04-02-03,A04-02...",NaN,NaN,축산업인,"농축수산인,기관/시설",0.0,99.0,0.0,0.0
1,74999,458000000382,장애 입양아동 의료비 지원,오프라인,있음,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-03-03,A09-09-01, A09-01-00",NaN,NaN,"장애인,입양가정",6.0,12.0,0.0,0.0
2,74998,000000402300,행려자 귀향여비 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-00,NaN,NaN,NaN,0.0,99.0,0.0,0.0
3,74997,458000000253,농산물 우수관리 시설 보완 지원(GAP),오프라인,NaN,NaN,NaN,NaN,NaN,"중소기업,소상공인,예비창업자",...,NaN,"A04-02-01,A04-02-03,A04-02-04,A04-02-04,A04-02...",A09-01-00,NaN,NaN,"농축수산인,기관/시설",0.0,99.0,0.0,0.0
4,74996,644000000251,충청남도 공공갈등 예방과 조정 지원,NaN,있음,NaN,NaN,NaN,NaN,중소기업,...,NaN,"A04-02-01,A04-02-02,A04-03-01,A04-03-02,A04-04...",A09-09-01,NaN,NaN,NaN,0.0,99.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,60005,485000000371,의료기관 결핵 환자 접촉자 검진비 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-03-03,전체,NaN,NaN,0.0,99.0,0.0,0.0
14996,60004,485000000370,의료급여수급자 일반 건강검진 지원,NaN,NaN,NaN,"무주택 세대주, 무주택 세대원, 주택 세대주, 주택 세대원",NaN,NaN,NaN,...,NaN,NaN,"A09-03-03, A09-01-00",전체,NaN,기관/시설,0.0,99.0,0.0,40.0
14997,60003,485000000363,유망 예비 농업인 및 우수 농업경영인 대상 창업 자금 등 융자 지원(후계농업경영인 육성),NaN,NaN,NaN,NaN,무관,NaN,NaN,...,NaN,NaN,A09-01-02,전체,NaN,농축수산인,18.0,49.0,0.0,0.0
14998,60002,485000000361,우수 후계농업경영인 추가 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-02,전체,NaN,농축수산인,0.0,99.0,0.0,0.0
14999,60001,483000000355,농산물 우수관리제도GAP 인증신청 수수료 지원,NaN,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업, 근로자/직장인",...,NaN,"A04-05-00, A04-06-00",A09-01-00,나주시,NaN,농축수산인,0.0,99.0,0.0,0.0

In [230]:
# 정책ID 누락 확인
for i in range(60001,75001):
    if i not in list(policy['정책ID']):
        print(i)

### 시군구 처리

In [243]:
df = pd.read_excel('policy_metetable(D조).xlsx')
df.head()

,정책ID,정책서비스ID,서비스명,소관기관,소관기관유형,소관기관.1,문의처전화번호,소관기관유형.1,온라인신청사이트URL,생애주기,...,태그-자녀상세,태그-직장상세,태그-지원유형상세,태그-지역(시군구),태그-대상특성상세,태그-대상특성,태그-대상연령시작,태그-대상연령끝,태그-중위소득시작,태그-중위소득끝
0,60001,483000000355,농산물 우수관리제도GAP 인증신청 수수료 지원,전라남도 나주시,시군구,전라남도 나주시,061-339-7393,시군구,NaN,중장년,...,NaN,"협회/단체/기타서비스업,협회/단체/기타서비스업,협회/단체/기타서비스업",NaN,NaN,NaN,"농축수산인,기관/시설",0,99,0,0
1,60002,485000000361,우수 후계농업경영인 추가 지원,전라남도 담양군,시군구,전라남도 담양군,380-2712,시군구,NaN,청년||중장년,...,NaN,"경영/사무/금융/보험직,경영/사무/금융/보험직,농업/축산업/어업,농업/축산업/어업,...",NaN,NaN,NaN,농축수산인,0,99,0,0
2,60003,485000000363,유망 예비 농업인 및 우수 농업경영인 대상 창업 자금 등 융자 지원(후계농업경영인 육성),전라남도 담양군,시군구,전라남도 담양군,380-2712,시군구,NaN,청년||중장년,...,NaN,"경영/사무/금융/보험직,경영/사무/금융/보험직,농업/축산업/어업,농업/축산업/어업,...",NaN,NaN,NaN,농축수산인,0,99,0,0
3,60004,485000000370,의료급여수급자 일반 건강검진 지원,전라남도 담양군,시군구,전라남도 담양군,061-380-3993,시군구,NaN,청년||중장년,...,NaN,NaN,의료,NaN,NaN,NaN,0,99,0,0
4,60005,485000000371,의료기관 결핵 환자 접촉자 검진비 지원,전라남도 담양군,시군구,전라남도 담양군,061-380-3978,시군구,NaN,영·유아||아동·청소년||청년||중장년||노년기,...,NaN,NaN,의료,NaN,NaN,NaN,0,99,0,0

In [244]:
df_p = df[['정책ID', '소관기관']]
df_p.head()

    정책ID      소관기관
0  60001  전라남도 나주시
1  60002  전라남도 담양군
2  60003  전라남도 담양군
3  60004  전라남도 담양군
4  60005  전라남도 담양군

In [245]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   정책ID    15000 non-null  int64
 1   소관기관    15000 non-null  object
dtypes: int64(1), object(1)
memory usage: 234.5+ KB

In [246]:
df_p['태그-지역(시도)'] = df_p['소관기관'].str.split(' ').str.get(0)
df_p['태그-지역(시군구)'] = df_p['소관기관'].str.split(' ').str.get(1)
df_p.head()

C:\Users\82105\anaconda3\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

    정책ID      소관기관 태그-지역(시도) 태그-지역(시군구)
0  60001  전라남도 나주시      전라남도        나주시
1  60002  전라남도 담양군      전라남도        담양군
2  60003  전라남도 담양군      전라남도        담양군
3  60004  전라남도 담양군      전라남도        담양군
4  60005  전라남도 담양군      전라남도        담양군

In [247]:
df_p['태그-지역(시도)'].value_counts(sort=False)

전라남도       4602
전라북도       5119
제주특별자치도     475
충청남도       4804
Name: 태그-지역(시도), dtype: int64

In [248]:
df_p['소관기관'].value_counts(sort=False)

전라남도 나주시     53
전라남도 담양군    214
전라남도 목포시    230
전라남도 무안군    136
전라남도 광양시     83
전라남도 신안군    216
전라남도 순천시    350
전라남도 보성군    239
전라남도 구례군    121
전라남도 여수시    272
전라남도 영광군    261
전라남도 함평군    216
전라남도 완도군    201
전라남도 장성군    140
전라남도 진도군    213
전라남도 장흥군    256
전라남도 해남군    317
전라남도 화순군    233
전라남도 곡성군     99
전라남도 강진군    154
전라남도 고흥군    377
전라남도 영암군    218
전라남도          3
전라북도 장수군    313
전라북도 무주군    285
전라북도 정읍시    311
전라북도        347
전라북도 임실군    298
전라북도 김제시    385
전라북도 순창군    328
전라북도 익산시    499
전라북도 고창군    314
전라북도 남원시    267
전라북도 완주군    334
전라북도 부안군    300
전라북도 전주시    346
전라북도 진안군    438
전라북도 군산시    354
제주특별자치도     475
충청남도 예산군    296
충청남도 서천군    177
충청남도 보령시    254
충청남도        406
충청남도 부여군    288
충청남도 천안시    253
충청남도 홍성군    213
충청남도 태안군    285
충청남도 서산시    342
충청남도 금산군    307
충청남도 논산시    421
충청남도 당진시    348
충청남도 아산시    290
충청남도 계룡시    230
충청남도 청양군    323
충청남도 공주시    371
Name: 소관기관, dtype: int64

In [249]:
df_p['태그-지역(시군구)'][df_p['태그-지역(시군구)'].isnull()] = '전체'

<ipython-input-249-223ffb35bf0e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][df_p['태그-지역(시군구)'].isnull()] = '전체'
C:\Users\82105\anaconda3\lib\site-packages\pandas\core\generic.py:8861: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [250]:
for i in range(len(df_p)):
    if df_p['태그-지역(시도)'][i] == '충청남도':
        if df_p['태그-지역(시군구)'][i] == '전체':
            df_p['태그-지역(시군구)'][i] = 'A01-12-00'
        if df_p['태그-지역(시군구)'][i] == '천안시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-01'
        if df_p['태그-지역(시군구)'][i] == '공주시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-02'
        if df_p['태그-지역(시군구)'][i] == '보령시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-03'
        if df_p['태그-지역(시군구)'][i] == '아산시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-04'
        if df_p['태그-지역(시군구)'][i] == '서산시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-05'
        if df_p['태그-지역(시군구)'][i] == '논산시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-06'
        if df_p['태그-지역(시군구)'][i] == '계룡시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-07'
        if df_p['태그-지역(시군구)'][i] == '당진시':
            df_p['태그-지역(시군구)'][i] = 'A01-12-08'
        if df_p['태그-지역(시군구)'][i] == '금산군':
            df_p['태그-지역(시군구)'][i] = 'A01-12-09'
        if df_p['태그-지역(시군구)'][i] == '부여군':
            df_p['태그-지역(시군구)'][i] = 'A01-12-10'
        if df_p['태그-지역(시군구)'][i] == '서천군':
            df_p['태그-지역(시군구)'][i] = 'A01-12-11'
        if df_p['태그-지역(시군구)'][i] == '청양군':
            df_p['태그-지역(시군구)'][i] = 'A01-12-12'
        if df_p['태그-지역(시군구)'][i] == '홍성군':
            df_p['태그-지역(시군구)'][i] = 'A01-12-13'
        if df_p['태그-지역(시군구)'][i] == '예산군':
            df_p['태그-지역(시군구)'][i] = 'A01-12-14'
        if df_p['태그-지역(시군구)'][i] == '태안군':
            df_p['태그-지역(시군구)'][i] = 'A01-12-15'
    
    if df_p['태그-지역(시도)'][i] == '전라북도':
        if df_p['태그-지역(시군구)'][i] == '전체':
            df_p['태그-지역(시군구)'][i] = 'A01-13-00'
        if df_p['태그-지역(시군구)'][i] == '전주시':
            df_p['태그-지역(시군구)'][i] = 'A01-13-01'
        if df_p['태그-지역(시군구)'][i] == '군산시':
            df_p['태그-지역(시군구)'][i] = 'A01-13-02'
        if df_p['태그-지역(시군구)'][i] == '익산시':
            df_p['태그-지역(시군구)'][i] = 'A01-13-03'
        if df_p['태그-지역(시군구)'][i] == '정읍시':
            df_p['태그-지역(시군구)'][i] = 'A01-13-04'
        if df_p['태그-지역(시군구)'][i] == '남원시':
            df_p['태그-지역(시군구)'][i] = 'A01-13-05'
        if df_p['태그-지역(시군구)'][i] == '김제시':
            df_p['태그-지역(시군구)'][i] = 'A01-13-06'
        if df_p['태그-지역(시군구)'][i] == '완주군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-07'
        if df_p['태그-지역(시군구)'][i] == '진안군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-08'
        if df_p['태그-지역(시군구)'][i] == '무주군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-09'
        if df_p['태그-지역(시군구)'][i] == '장수군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-10'
        if df_p['태그-지역(시군구)'][i] == '임실군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-11'
        if df_p['태그-지역(시군구)'][i] == '순창군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-12'
        if df_p['태그-지역(시군구)'][i] == '고창군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-13'
        if df_p['태그-지역(시군구)'][i] == '부안군':
            df_p['태그-지역(시군구)'][i] = 'A01-13-14'
            
    if df_p['태그-지역(시도)'][i] == '전라남도':
        if df_p['태그-지역(시군구)'][i] == '전체':
            df_p['태그-지역(시군구)'][i] = 'A01-14-00'
        if df_p['태그-지역(시군구)'][i] == '목포시':
            df_p['태그-지역(시군구)'][i] = 'A01-14-01'
        if df_p['태그-지역(시군구)'][i] == '여수시':
            df_p['태그-지역(시군구)'][i] = 'A01-14-02'
        if df_p['태그-지역(시군구)'][i] == '순천시':
            df_p['태그-지역(시군구)'][i] = 'A01-14-03'
        if df_p['태그-지역(시군구)'][i] == '나주시':
            df_p['태그-지역(시군구)'][i] = 'A01-14-04'
        if df_p['태그-지역(시군구)'][i] == '광양시':
            df_p['태그-지역(시군구)'][i] = 'A01-14-05'
        if df_p['태그-지역(시군구)'][i] == '담양군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-06'
        if df_p['태그-지역(시군구)'][i] == '곡성군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-07'
        if df_p['태그-지역(시군구)'][i] == '구례군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-08'
        if df_p['태그-지역(시군구)'][i] == '고흥군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-09'
        if df_p['태그-지역(시군구)'][i] == '보성군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-10'
        if df_p['태그-지역(시군구)'][i] == '화순군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-11'
        if df_p['태그-지역(시군구)'][i] == '장흥군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-12'
        if df_p['태그-지역(시군구)'][i] == '강진군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-13'
        if df_p['태그-지역(시군구)'][i] == '해남군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-14'
        if df_p['태그-지역(시군구)'][i] == '영암군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-15'
        if df_p['태그-지역(시군구)'][i] == '무안군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-16'
        if df_p['태그-지역(시군구)'][i] == '함평군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-17'
        if df_p['태그-지역(시군구)'][i] == '영광군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-18'
        if df_p['태그-지역(시군구)'][i] == '장성군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-19'
        if df_p['태그-지역(시군구)'][i] == '완도군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-20'
        if df_p['태그-지역(시군구)'][i] == '진도군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-21'
        if df_p['태그-지역(시군구)'][i] == '신안군':
            df_p['태그-지역(시군구)'][i] = 'A01-14-22'
    
    if df_p['태그-지역(시도)'][i] == '제주특별자치도':
        if df_p['태그-지역(시군구)'][i] == '전체':
            df_p['태그-지역(시군구)'][i] = ''

<ipython-input-250-e8e46a07caa2>:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-04'
<ipython-input-250-e8e46a07caa2>:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-06'
<ipython-input-250-e8e46a07caa2>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-01'
<ipython-input-250-e8e46a07caa2>:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-16'
<ipython-input-250-e8e46a07caa2>:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-05'
<ipython-input-250-e8e46a07caa2>:114: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-22'
<ipython-input-250-e8e46a07caa2>:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-03'
<ipython-input-250-e8e46a07caa2>:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-10'
<ipython-input-250-e8e46a07caa2>:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-08'
<ipython-input-250-e8e46a07caa2>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-02'
<ipython-input-250-e8e46a07caa2>:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-18'
<ipython-input-250-e8e46a07caa2>:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-17'
<ipython-input-250-e8e46a07caa2>:110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-20'
<ipython-input-250-e8e46a07caa2>:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-19'
<ipython-input-250-e8e46a07caa2>:112: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-21'
<ipython-input-250-e8e46a07caa2>:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-12'
<ipython-input-250-e8e46a07caa2>:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-14'
<ipython-input-250-e8e46a07caa2>:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-11'
<ipython-input-250-e8e46a07caa2>:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-07'
<ipython-input-250-e8e46a07caa2>:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-13'
<ipython-input-250-e8e46a07caa2>:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-09'
<ipython-input-250-e8e46a07caa2>:100: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-15'
<ipython-input-250-e8e46a07caa2>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-14-00'
<ipython-input-250-e8e46a07caa2>:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-10'
<ipython-input-250-e8e46a07caa2>:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-09'
<ipython-input-250-e8e46a07caa2>:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-04'
<ipython-input-250-e8e46a07caa2>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-00'
<ipython-input-250-e8e46a07caa2>:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-11'
<ipython-input-250-e8e46a07caa2>:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-06'
<ipython-input-250-e8e46a07caa2>:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-12'
<ipython-input-250-e8e46a07caa2>:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-03'
<ipython-input-250-e8e46a07caa2>:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-13'
<ipython-input-250-e8e46a07caa2>:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-05'
<ipython-input-250-e8e46a07caa2>:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-07'
<ipython-input-250-e8e46a07caa2>:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-14'
<ipython-input-250-e8e46a07caa2>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-01'

<ipython-input-250-e8e46a07caa2>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-08'
<ipython-input-250-e8e46a07caa2>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-13-02'
<ipython-input-250-e8e46a07caa2>:118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = ''
<ipython-input-250-e8e46a07caa2>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-14'
<ipython-input-250-e8e46a07caa2>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-11'
<ipython-input-250-e8e46a07caa2>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-03'
<ipython-input-250-e8e46a07caa2>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-00'
<ipython-input-250-e8e46a07caa2>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-10'
<ipython-input-250-e8e46a07caa2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-01'
<ipython-input-250-e8e46a07caa2>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-13'
<ipython-input-250-e8e46a07caa2>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-15'
<ipython-input-250-e8e46a07caa2>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-05'
<ipython-input-250-e8e46a07caa2>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-09'
<ipython-input-250-e8e46a07caa2>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-06'
<ipython-input-250-e8e46a07caa2>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-08'
<ipython-input-250-e8e46a07caa2>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-04'
<ipython-input-250-e8e46a07caa2>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-07'
<ipython-input-250-e8e46a07caa2>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-12'
<ipython-input-250-e8e46a07caa2>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p['태그-지역(시군구)'][i] = 'A01-12-02'

In [251]:
df_p = df_p.drop(['소관기관', '태그-지역(시도)'], 1)
df_p.sort_values(by='정책ID', ascending=False, inplace=True)

<ipython-input-251-4a49dfa7233d>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_p = df_p.drop(['소관기관', '태그-지역(시도)'], 1)

In [254]:
df_p.head()

        정책ID 태그-지역(시군구)
14999  75000  A01-12-11
14998  74999  A01-12-11
14997  74998  A01-12-11
14996  74997  A01-12-11
14995  74996  A01-12-00

In [255]:
policy.columns

Index(['정책ID', '정책서비스ID', '서비스명', '신청절차', '자녀', '수집유형', '가구원', '성별', '학력',
       '직장', '결혼', '지원유형', '지역(시도)', '관심상황특성', '자녀상세', '직장상세', '지원유형상세',
       '지역(시군구)', '대상특성상세', '대상특성', '대상연령시작', '대상연령끝', '중위소득기준-시작',
       '중위소득기준-종료'],
      dtype='object')

In [256]:
policy['지역(시군구)'] = df_p['태그-지역(시군구)']
policy

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득기준-시작,중위소득기준-종료
0,75000,458000000210,6차산업 자금 융자 지원,NaN,NaN,NaN,NaN,NaN,NaN,"중소기업,예비창업자",...,NaN,"A04-02-01,A04-02-01,A04-02-03,A04-02-03,A04-02...",NaN,A01-14-04,축산업인,"농축수산인,기관/시설",0.0,99.0,0.0,0.0
1,74999,458000000382,장애 입양아동 의료비 지원,오프라인,있음,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-03-03,A09-09-01, A09-01-00",A01-14-06,NaN,"장애인,입양가정",6.0,12.0,0.0,0.0
2,74998,000000402300,행려자 귀향여비 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-00,A01-14-06,NaN,NaN,0.0,99.0,0.0,0.0
3,74997,458000000253,농산물 우수관리 시설 보완 지원(GAP),오프라인,NaN,NaN,NaN,NaN,NaN,"중소기업,소상공인,예비창업자",...,NaN,"A04-02-01,A04-02-03,A04-02-04,A04-02-04,A04-02...",A09-01-00,A01-14-06,NaN,"농축수산인,기관/시설",0.0,99.0,0.0,0.0
4,74996,644000000251,충청남도 공공갈등 예방과 조정 지원,NaN,있음,NaN,NaN,NaN,NaN,중소기업,...,NaN,"A04-02-01,A04-02-02,A04-03-01,A04-03-02,A04-04...",A09-09-01,A01-14-06,NaN,NaN,0.0,99.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,60005,485000000371,의료기관 결핵 환자 접촉자 검진비 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-03-03,A01-12-00,NaN,NaN,0.0,99.0,0.0,0.0
14996,60004,485000000370,의료급여수급자 일반 건강검진 지원,NaN,NaN,NaN,"무주택 세대주, 무주택 세대원, 주택 세대주, 주택 세대원",NaN,NaN,NaN,...,NaN,NaN,"A09-03-03, A09-01-00",A01-12-11,NaN,기관/시설,0.0,99.0,0.0,40.0
14997,60003,485000000363,유망 예비 농업인 및 우수 농업경영인 대상 창업 자금 등 융자 지원(후계농업경영인 육성),NaN,NaN,NaN,NaN,무관,NaN,NaN,...,NaN,NaN,A09-01-02,A01-12-11,NaN,농축수산인,18.0,49.0,0.0,0.0
14998,60002,485000000361,우수 후계농업경영인 추가 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-02,A01-12-11,NaN,농축수산인,0.0,99.0,0.0,0.0
14999,60001,483000000355,농산물 우수관리제도GAP 인증신청 수수료 지원,NaN,NaN,NaN,NaN,NaN,NaN,"소상공인, 중소기업, 근로자/직장인",...,NaN,"A04-05-00, A04-06-00",A09-01-00,A01-12-11,NaN,농축수산인,0.0,99.0,0.0,0.0

In [260]:
policy.to_excel('강민주_직장상세,concat,내림차순,누락확인,시군구처리.xlsx', encoding='utf-8-sig')

### Unique&2-9 + 직장/직장상세

In [134]:
uniq = pd.read_excel('박민지_unique (5).xlsx')
work = pd.read_csv('정책ID_직장_직장상세_태그코드적용.csv')

In [135]:
uniq.head()

,Unnamed: 0,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득시작,중위소득끝
0,0,60016,480000000383,건강가정 복지증진 및 지원,온라인,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-03-04,A09-09-01",NaN,NaN,NaN,0,99,0,0
1,1,60022,480000000433,다문화가정 인터넷 사용요금 지원,오프라인,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-00,NaN,NaN,다문화가족,0,99,0,0
2,2,60042,480000000477,수의사 연수교육 지원,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"A09-09-01, A09-01-00",NaN,NaN,농축수산인,0,99,0,0
3,3,60058,480000000498,국공립 어린이집 확충 지원,NaN,있음,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-09-01,NaN,NaN,NaN,0,5,0,0
4,4,60068,495000000215,2018년 농산물마케팅 지원(농산물마케팅 지원사업),온라인,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,기관/시설,0,99,0,0

In [136]:
work.head()

    정책ID            태그-직장                                            태그-직장상세
0  60001  중소기업,소상공인,예비창업자  A04-02-01,A04-02-03,A04-02-03,A04-02-06,A04-03...
1  60002       중소기업,예비창업자                                A04-02-01,A04-03-01
2  60003       중소기업,예비창업자  A04-02-01,A04-02-02,A04-03-01,A04-03-02,A04-04...
3  60004              NaN                                A04-02-05,A04-03-05
4  60005              NaN                                A04-02-05,A04-03-05

In [137]:
uniq = uniq.drop('Unnamed: 0', 1)
uniq.columns

<ipython-input-137-f45d480b2069>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  uniq = uniq.drop('Unnamed: 0', 1)

Index(['정책ID', '정책서비스ID', '서비스명', '신청절차', '자녀', '수집유형', '가구원', '성별', '학력',
       '직장', '결혼', '지원유형', '지역(시도)', '관심상황특성', '자녀상세', '직장상세', '지원유형상세',
       '지역(시군구)', '대상특성상세', '대상특성', '대상연령시작', '대상연령끝', '중위소득시작', '중위소득끝'],
      dtype='object')

In [138]:
work.columns = ['정책ID', '직장', '직장상세']
work

,정책ID,직장,직장상세
0,60001,"중소기업,소상공인,예비창업자","A04-02-01,A04-02-03,A04-02-03,A04-02-06,A04-03..."
1,60002,"중소기업,예비창업자","A04-02-01,A04-03-01"
2,60003,"중소기업,예비창업자","A04-02-01,A04-02-02,A04-03-01,A04-03-02,A04-04..."
3,60004,NaN,"A04-02-05,A04-03-05"
4,60005,NaN,"A04-02-05,A04-03-05"
...,...,...,...
14995,74996,중소기업,"A04-02-01,A04-02-02,A04-03-01,A04-03-02,A04-04..."
14996,74997,"중소기업,소상공인,예비창업자","A04-02-01,A04-02-03,A04-02-04,A04-02-04,A04-02..."
14997,74998,NaN,"A04-02-04,A04-03-04"
14998,74999,NaN,"A04-02-05,A04-02-05,A04-03-05,A04-03-05,A04-04..."
14999,75000,"중소기업,예비창업자","A04-02-01,A04-02-01,A04-02-03,A04-02-03,A04-02..."

In [139]:
work = pd.merge(uniq, work, on='정책ID')
work.head()

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장_x,...,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득시작,중위소득끝,직장_y,직장상세_y
0,60016,480000000383,건강가정 복지증진 및 지원,온라인,NaN,NaN,NaN,NaN,NaN,NaN,...,"A09-03-04,A09-09-01",NaN,NaN,NaN,0,99,0,0,NaN,"A04-02-02,A04-03-02,A04-04-04,A04-04-05,A04-05..."
1,60022,480000000433,다문화가정 인터넷 사용요금 지원,오프라인,NaN,NaN,NaN,NaN,NaN,NaN,...,A09-01-00,NaN,NaN,다문화가족,0,99,0,0,NaN,NaN
2,60042,480000000477,수의사 연수교육 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"A09-09-01, A09-01-00",NaN,NaN,농축수산인,0,99,0,0,NaN,"A04-02-02,A04-02-03,A04-02-03,A04-02-05,A04-03..."
3,60058,480000000498,국공립 어린이집 확충 지원,NaN,있음,NaN,NaN,NaN,NaN,NaN,...,A09-09-01,NaN,NaN,NaN,0,5,0,0,NaN,"A04-02-02,A04-03-02,A04-04-04,A04-04-05,A04-04..."
4,60068,495000000215,2018년 농산물마케팅 지원(농산물마케팅 지원사업),온라인,NaN,NaN,NaN,NaN,NaN,"소상공인,중소기업",...,NaN,NaN,NaN,기관/시설,0,99,0,0,"중소기업,소상공인,근로자/직장인,예비창업자","A04-02-01,A04-02-03,A04-02-03,A04-03-01,A04-03..."

In [140]:
work.columns

Index(['정책ID', '정책서비스ID', '서비스명', '신청절차', '자녀', '수집유형', '가구원', '성별', '학력',
       '직장_x', '결혼', '지원유형', '지역(시도)', '관심상황특성', '자녀상세', '직장상세_x', '지원유형상세',
       '지역(시군구)', '대상특성상세', '대상특성', '대상연령시작', '대상연령끝', '중위소득시작', '중위소득끝',
       '직장_y', '직장상세_y'],
      dtype='object')

In [141]:
work['직장_x'], work['직장상세_x'] = work['직장_y'], work['직장상세_y']
work.head()

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장_x,...,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득시작,중위소득끝,직장_y,직장상세_y
0,60016,480000000383,건강가정 복지증진 및 지원,온라인,NaN,NaN,NaN,NaN,NaN,NaN,...,"A09-03-04,A09-09-01",NaN,NaN,NaN,0,99,0,0,NaN,"A04-02-02,A04-03-02,A04-04-04,A04-04-05,A04-05..."
1,60022,480000000433,다문화가정 인터넷 사용요금 지원,오프라인,NaN,NaN,NaN,NaN,NaN,NaN,...,A09-01-00,NaN,NaN,다문화가족,0,99,0,0,NaN,NaN
2,60042,480000000477,수의사 연수교육 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"A09-09-01, A09-01-00",NaN,NaN,농축수산인,0,99,0,0,NaN,"A04-02-02,A04-02-03,A04-02-03,A04-02-05,A04-03..."
3,60058,480000000498,국공립 어린이집 확충 지원,NaN,있음,NaN,NaN,NaN,NaN,NaN,...,A09-09-01,NaN,NaN,NaN,0,5,0,0,NaN,"A04-02-02,A04-03-02,A04-04-04,A04-04-05,A04-04..."
4,60068,495000000215,2018년 농산물마케팅 지원(농산물마케팅 지원사업),온라인,NaN,NaN,NaN,NaN,NaN,"중소기업,소상공인,근로자/직장인,예비창업자",...,NaN,NaN,NaN,기관/시설,0,99,0,0,"중소기업,소상공인,근로자/직장인,예비창업자","A04-02-01,A04-02-03,A04-02-03,A04-03-01,A04-03..."

In [142]:
work.drop(['직장_y','직장상세_y'], 1, inplace=True)
work.rename(columns={'직장_x':'직장', '직장상세_x':'직장상세'}, inplace=True)
work.head()

<ipython-input-142-ba6999cc111d>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  work.drop(['직장_y','직장상세_y'], 1, inplace=True)

,정책ID,정책서비스ID,서비스명,신청절차,자녀,수집유형,가구원,성별,학력,직장,...,자녀상세,직장상세,지원유형상세,지역(시군구),대상특성상세,대상특성,대상연령시작,대상연령끝,중위소득시작,중위소득끝
0,60016,480000000383,건강가정 복지증진 및 지원,온라인,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"A04-02-02,A04-03-02,A04-04-04,A04-04-05,A04-05...","A09-03-04,A09-09-01",NaN,NaN,NaN,0,99,0,0
1,60022,480000000433,다문화가정 인터넷 사용요금 지원,오프라인,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,A09-01-00,NaN,NaN,다문화가족,0,99,0,0
2,60042,480000000477,수의사 연수교육 지원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"A04-02-02,A04-02-03,A04-02-03,A04-02-05,A04-03...","A09-09-01, A09-01-00",NaN,NaN,농축수산인,0,99,0,0
3,60058,480000000498,국공립 어린이집 확충 지원,NaN,있음,NaN,NaN,NaN,NaN,NaN,...,NaN,"A04-02-02,A04-03-02,A04-04-04,A04-04-05,A04-04...",A09-09-01,NaN,NaN,NaN,0,5,0,0
4,60068,495000000215,2018년 농산물마케팅 지원(농산물마케팅 지원사업),온라인,NaN,NaN,NaN,NaN,NaN,"중소기업,소상공인,근로자/직장인,예비창업자",...,NaN,"A04-02-01,A04-02-03,A04-02-03,A04-03-01,A04-03...",NaN,NaN,NaN,기관/시설,0,99,0,0

In [143]:
work.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6576 entries, 0 to 6575
Data columns (total 24 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   정책ID     6576 non-null   int64
 1   정책서비스ID  6576 non-null   object
 2   서비스명     6576 non-null   object
 3   신청절차     2751 non-null   object
 4   자녀       1989 non-null   object
 5   수집유형     0 non-null      float64
 6   가구원      216 non-null    object
 7   성별       221 non-null    object
 8   학력       67 non-null     object
 9   직장       2318 non-null   object
 10  결혼       127 non-null    object
 11  지원유형     6041 non-null   object
 12  지역(시도)   0 non-null      float64
 13  관심상황특성   460 non-null    object
 14  자녀상세     169 non-null    object
 15  직장상세     6107 non-null   object
 16  지원유형상세   5625 non-null   object
 17  지역(시군구)  0 non-null      float64
 18  대상특성상세   358 non-null    object
 19  대상특성     4419 non-null   object
 20  대상연령시작   6576 non-null   int64
 21  대상연령끝    6576 non-null   int64
 22  중위소득시작   6576 non-null   int64
 23  중위소득끝    6576 non-null   int64
dtypes: float64(3), int64(5), object(16)
memory usage: 1.3+ MB

In [144]:
work.to_csv('직장상세태그코드적용+uniq&2~9.csv', sep=',', encoding='utf-8-sig')